# Generated by Django 2.2 on 2019-08-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobject',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='files/input_files/'),
        ),
    ]
