# Generated by Django 2.0 on 2019-08-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobject',
            name='has_errors',
            field=models.BooleanField(default=False),
        ),
    ]
