# Generated by Django 2.2 on 2019-08-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_auto_20190823_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileobject',
            name='input_file_url',
        ),
    ]
